CREATE TABLE IF NOT EXISTS user_settings (
    owner CHAR(36) NOT NULL PRIMARY KEY,
    data MEDIUMBLOB NOT NULL,
    version INT NOT NULL DEFAULT 1,
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    FOREIGN KEY (owner) REFERENCES users(uuid) ON DELETE CASCADE
);
